# Generated by Django 5.1.2 on 2024-11-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
