# Generated by Django 5.1.2 on 2024-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_liked_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author_username',
            field=models.TextField(default=''),
        ),
    ]
