# Generated by Django 5.1.2 on 2024-11-22 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_liked_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='liked_by_user',
            field=models.ManyToManyField(related_name='liked_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
