# Generated by Django 5.1.2 on 2024-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_author_profile_picture_post_community_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_picture',
            field=models.ImageField(default='../assets/default_profile_picture.png', upload_to=''),
        ),
    ]
