# Generated by Django 5.1.2 on 2024-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_post_post_picture_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='warning',
            field=models.TextField(default=''),
        ),
    ]
