# Generated by Django 5.1.2 on 2024-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_profile_is_health_professional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='warn_author_username',
            field=models.TextField(default=''),
        ),
    ]
