# Generated by Django 5.1.2 on 2024-12-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_post_warn_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_is_health_professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='author_is_health_professional',
            field=models.BooleanField(default=False),
        ),
    ]
